site_name: PCA Classification Visualizer
theme:
  name: material
  palette:
    primary: indigo
    accent: light blue
nav:
  - Home: index.md
  - How to Use: usage.md
  - Features: features.md
  - FAQ: faq.md
